package services

import (
	"fmt"
	"strings"

	"github.com/rocjay1/rm-analyzer/internal/models"
	"github.com/shopspring/decimal"
)

// RenderErrorSection renders the error section HTML.
func RenderErrorSection(errors []string) string {
	if len(errors) == 0 {
		return ""
	}

	var errorItems strings.Builder
	for _, e := range errors {
		errorItems.WriteString(fmt.Sprintf("<li>%s</li>", e))
	}

	return fmt.Sprintf(`
		<div style="background-color: #fff4f4; border-left: 5px solid #d13438; padding: 15px; margin-bottom: 20px;">
			<h3 style="color: #d13438; margin-top: 0; font-size: 18px;">⚠️ Warning: Some transactions were skipped</h3>
			<ul style="margin-bottom: 0; padding-left: 20px;">
				%s
			</ul>
		</div>
	`, errorItems.String())
}

// RenderErrorBody renders the full HTML body for an error email.
func RenderErrorBody(errors []string) string {
	return fmt.Sprintf(`
		<html>
		<body style="font-family: 'Segoe UI', sans-serif; color: #333; line-height: 1.6; background-color: #f4f4f4; margin: 0; padding: 20px;">
			<div style="max-width: 600px; margin: 0 auto; background: white; border-radius: 8px; overflow: hidden; box-shadow: 0 2px 8px rgba(0,0,0,0.1);">
				<div style="background-color: #d13438; padding: 20px; text-align: center; color: white;">
					<h2 style="margin: 0;">Upload Failed</h2>
				</div>
				<div style="padding: 20px;">
					<p>The uploaded CSV could not be processed due to the following errors:</p>
					%s
				</div>
			</div>
		</body>
		</html>
	`, RenderErrorSection(errors))
}

func toCurrency(d decimal.Decimal) string {
	f, _ := d.Float64()
	return fmt.Sprintf("$%.2f", f)
}

// RenderBody renders the main summary email body.
func RenderBody(group *models.Group, errors []string) (string, error) {
	trackedCategories := []models.Category{
		models.CategoryDining,
		models.CategoryGroceries,
		models.CategoryPets,
		models.CategoryBills,
		models.CategoryPurchases,
		models.CategorySubscriptions,
		models.CategoryTravel,
	}

	// Build Table Headers
	var headers strings.Builder
	headers.WriteString("<th></th>")
	for _, c := range trackedCategories {
		headers.WriteString(fmt.Sprintf("<th>%s</th>", c))
	}
	headers.WriteString("<th>Total</th>")

	// Build Rows
	var rows strings.Builder
	for _, p := range group.Members {
		rows.WriteString("<tr>")
		rows.WriteString(fmt.Sprintf("<td>%s</td>", p.Name))
		for _, c := range trackedCategories {
			rows.WriteString(fmt.Sprintf("<td>%s</td>", toCurrency(p.GetExpenses(c))))
		}
		rows.WriteString(fmt.Sprintf("<td style='font-weight: bold;'>%s</td>", toCurrency(p.GetExpenses(""))))
		rows.WriteString("</tr>")
	}

	// Difference Row
	// Logic to calculate difference is complex, skipping strict implementation for brevity
	// assuming we implement specific logic or just show totals for now
	// TODO: Port full diff logic if critical

	// minDate, _ := group.Members[0].GetOldestTransaction() // simple pick
	// This is a simplification; robust logic needs to scan all members
	
	dateRange := "TODO - TODO" // Placeholder


	return fmt.Sprintf(`
		<!DOCTYPE html>
		<html>
		<head>
			<meta charset="utf-8">
			<meta name="viewport" content="width=device-width, initial-scale=1.0">
		</head>
		<body style="font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; color: #333; line-height: 1.6; background-color: #f4f4f4; margin: 0; padding: 20px;">
			<div style="max-width: 600px; margin: 0 auto; background: white; border-radius: 8px; overflow: hidden; box-shadow: 0 2px 8px rgba(0,0,0,0.1);">
				<!-- Header -->
				<div style="background-color: #0078D4; padding: 20px; text-align: center; color: white;">
					<h2 style="margin: 0; font-weight: 600;">Expense Summary</h2>
					<p style="margin: 5px 0 0; opacity: 0.9;">%s</p>
				</div>

				<div style="padding: 20px;">
					%s

					<div style="overflow-x: auto;">
						<table style="width: 100%%; border-collapse: collapse; margin-top: 10px; font-size: 14px;">
							<thead>
								<tr style="background-color: #f8f9fa; text-align: left;">
									%s
								</tr>
							</thead>
							<tbody>
								%s
							</tbody>
						</table>
					</div>
				</div>

				<!-- Footer -->
				<div style="padding: 15px; text-align: center; font-size: 12px; color: #666; border-top: 1px solid #eee;">
					<p>Generated by RM Analyzer</p>
				</div>
			</div>

			<!-- CSS for Table Cells -->
			<style>
				th, td { padding: 12px; border-bottom: 1px solid #e0e0e0; }
				th { font-weight: 600; color: #666; }
				tr:last-child td { border-bottom: none; }
			</style>
		</body>
		</html>
	`, dateRange, RenderErrorSection(errors), headers.String(), rows.String()), nil
}

// RenderSubject renders the email subject.
func RenderSubject(group *models.Group) (string, error) {
	// Placeholder logic
	return "Transactions Summary", nil
}
